"""
Validates the DDL syntax of converted PostgreSQL domains, views, functions/procedures, and triggers
against a live PostgreSQL database without making permanent changes (Dry-Run by default).
"""
import os
import re
import sys
from dataclasses import dataclass
from typing import List, Optional, Tuple

from config import get_postgres_connection, PostgresConfig, get_dump_path, DumpFiles
from utils import split_sql_statements as split_sql_content

DEFAULT_TARGET_FILES = [
    get_dump_path(DumpFiles.DOMAINS_PG),
    get_dump_path(DumpFiles.VIEWS_PG),
    get_dump_path(DumpFiles.PROCEDURES_PG),
    get_dump_path(DumpFiles.TRIGGERS_PG)
]


@dataclass
class SQLStatement:
    file_name: str
    object_type: str  # 'DOMAIN', 'VIEW', 'FUNCTION', 'TRIGGER', 'OTHER'
    object_name: str
    sql: str
    start_line: int


@dataclass
class ValidationResult:
    statement: SQLStatement
    success: bool
    error_message: Optional[str] = None
    pg_code: Optional[str] = None


def split_sql_statements(file_path: str, allow_missing: bool = False) -> List[SQLStatement]:
    """
    Parses a PostgreSQL SQL file into individual SQLStatement objects.
    The low-level splitting (quotes, comments, dollar-quoting) lives in sql_splitter.
    """
    if not os.path.exists(file_path):
        if not allow_missing:
            raise FileNotFoundError(f"Target SQL file '{file_path}' not found.")
        print(f"[WARNING] File '{file_path}' not found. Skipping.")
        return []

    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    statements = []
    for sql, start_line in split_sql_content(content):
        obj_type, obj_name = identify_object(sql)
        statements.append(
            SQLStatement(
                file_name=os.path.basename(file_path),
                object_type=obj_type,
                object_name=obj_name,
                sql=sql,
                start_line=start_line
            )
        )

    return statements


def identify_object(sql_text: str) -> Tuple[str, str]:
    """
    Identifies the SQL object type and name from statement text.
    """
    clean_sql = re.sub(r'--[^\n]*\n', '\n', sql_text)
    clean_sql = re.sub(r'/\*.*?\*/', '', clean_sql, flags=re.DOTALL).strip()

    # Domain: schema-qualified quoted form (generated by DdlExporter, possibly nested in a
    # DO block), plain quoted form, or bare unquoted form
    m = (re.search(r'CREATE\s+DOMAIN\s+(?:[a-zA-Z0-9_]+\.)?"([^"]+)"', clean_sql, re.IGNORECASE)
         or re.search(r'CREATE\s+DOMAIN\s+([a-zA-Z0-9_]+)', clean_sql, re.IGNORECASE))
    if m:
        return 'DOMAIN', m.group(1)

    # View
    m = re.search(r'CREATE\s+(?:OR\s+REPLACE\s+)?VIEW\s+"?([a-zA-Z0-9_]+)"?', clean_sql, re.IGNORECASE)
    if m:
        return 'VIEW', m.group(1)

    # Function
    m = re.search(r'CREATE\s+(?:OR\s+REPLACE\s+)?FUNCTION\s+"?([a-zA-Z0-9_]+)"?\s*\(', clean_sql, re.IGNORECASE)
    if m:
        return 'FUNCTION', m.group(1)

    # Procedure
    m = re.search(r'CREATE\s+(?:OR\s+REPLACE\s+)?PROCEDURE\s+"?([a-zA-Z0-9_]+)"?\s*\(', clean_sql, re.IGNORECASE)
    if m:
        return 'PROCEDURE', m.group(1)

    # Trigger
    m = re.search(r'CREATE\s+TRIGGER\s+"?([a-zA-Z0-9_]+)"?\s+', clean_sql, re.IGNORECASE)
    if m:
        return 'TRIGGER', m.group(1)

    return 'OTHER', 'UNKNOWN'


def check_plpgsql_runtime_validity(
    cursor,
    function_names: Optional[List[str]] = None
) -> tuple[List[ValidationResult], List[tuple[str, str]]]:
    """
    Checks PL/pgSQL functions and triggers for runtime syntax and column/type errors
    using plpgsql_check_function_tb with proper OIDs and trigger relation IDs.
    Wraps each check in a SAVEPOINT to preserve transaction state on check failure.
    Returns (validation_results, runtime_issues).
    """
    validation_results: List[ValidationResult] = []
    runtime_issues: List[tuple[str, str]] = []

    try:
        cursor.execute("SELECT 1 FROM pg_extension WHERE extname = 'plpgsql_check';")
        if not cursor.fetchone():
            return validation_results, runtime_issues
    except Exception:
        return validation_results, runtime_issues

    filter_names = set(n.lower() for n in function_names) if function_names else None

    # 1. Inspect regular functions & procedures
    try:
        cursor.execute("""
            SELECT p.oid, p.proname, n.nspname
            FROM pg_proc p
            JOIN pg_namespace n ON n.oid = p.pronamespace
            WHERE n.nspname = 'public'
              AND p.prolang = (SELECT oid FROM pg_language WHERE lanname = 'plpgsql')
              AND p.prorettype <> (SELECT oid FROM pg_type WHERE typname = 'trigger');
        """)
        regular_funcs = cursor.fetchall()
    except Exception:
        regular_funcs = []

    # 2. Inspect trigger functions with their target relation IDs
    try:
        cursor.execute("""
            SELECT t.tgfoid, p.proname, t.tgrelid, c.relname, t.tgname
            FROM pg_trigger t
            JOIN pg_proc p ON p.oid = t.tgfoid
            JOIN pg_class c ON c.oid = t.tgrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE n.nspname = 'public' AND NOT t.tgisinternal;
        """)
        triggers = cursor.fetchall()
    except Exception:
        triggers = []

    check_targets = []
    for fn_oid, fn_name, nsp in regular_funcs:
        if filter_names is None or fn_name.lower() in filter_names:
            check_targets.append((fn_oid, 0, fn_name, 'FUNCTION'))

    for tg_foid, fn_name, tg_relid, rel_name, tg_name in triggers:
        if filter_names is None or fn_name.lower() in filter_names or tg_name.lower() in filter_names:
            check_targets.append((tg_foid, tg_relid, f"{tg_name} on {rel_name}", 'TRIGGER'))

    for idx, (f_oid, r_oid, obj_name, obj_type) in enumerate(check_targets, 1):
        sp_name = f"sp_plpgsql_check_{idx}"
        try:
            cursor.execute(f"SAVEPOINT {sp_name};")
            cursor.execute(
                "SELECT message, level, sqlstate, lineno, statement FROM plpgsql_check_function_tb(%s, %s);",
                (f_oid, r_oid)
            )
            rows = cursor.fetchall()
            cursor.execute(f"RELEASE SAVEPOINT {sp_name};")

            for msg, level, sqlstate, lineno, stmt_text in rows:
                desc = f"[{level}] {msg} (line {lineno})" if lineno else f"[{level}] {msg}"
                runtime_issues.append((obj_name, desc))
                if str(level).lower() == 'error':
                    validation_results.append(
                        ValidationResult(
                            statement=SQLStatement(
                                sql=stmt_text or f"-- plpgsql_check {obj_name}",
                                file_name="plpgsql_check",
                                start_line=lineno or 0,
                                object_type=obj_type,
                                object_name=obj_name
                            ),
                            success=False,
                            error_message=f"[plpgsql_check error] {msg} (line {lineno})",
                            pg_code=sqlstate
                        )
                    )
        except Exception as e:
            try:
                cursor.execute(f"ROLLBACK TO SAVEPOINT {sp_name};")
            except Exception:
                pass
            err_msg = str(e).strip()
            runtime_issues.append((obj_name, f"[check failure] {err_msg}"))

    return validation_results, runtime_issues


def run_ddl_validation(
    conn,
    target_files: List[str],
    apply_changes: bool = False,
    allow_missing_files: bool = False,
    allow_empty_files: bool = False
) -> tuple[List[ValidationResult], List[tuple[str, str]]]:
    """
    Executes each statement in sequence inside a PostgreSQL transaction using SAVEPOINTS.
    In dry-run mode (default), the entire transaction is rolled back at the end.
    Returns (results, runtime_issues).
    """
    if getattr(conn, 'autocommit', False):
        conn.autocommit = False
    cursor = conn.cursor()
    try:
        results: List[ValidationResult] = []
        all_statements: List[SQLStatement] = []
        for fpath in target_files:
            if not os.path.exists(fpath):
                if not allow_missing_files:
                    results.append(
                        ValidationResult(
                            statement=SQLStatement(
                                file_name=os.path.basename(fpath),
                                object_type="FILE",
                                object_name=fpath,
                                sql="",
                                start_line=0
                            ),
                            success=False,
                            error_message=f"Target file not found: '{fpath}'",
                            pg_code="FILE_NOT_FOUND"
                        )
                    )
                else:
                    print(f"[WARNING] File '{fpath}' not found. Skipping.")
                continue

            stmts = split_sql_statements(fpath, allow_missing=True)
            if not stmts:
                if not allow_empty_files:
                    results.append(
                        ValidationResult(
                            statement=SQLStatement(
                                file_name=os.path.basename(fpath),
                                object_type="FILE",
                                object_name=fpath,
                                sql="",
                                start_line=0
                            ),
                            success=False,
                            error_message=f"Target file '{fpath}' contains 0 SQL statements (empty file). Set allow_empty_files=True if permitted.",
                            pg_code="FILE_EMPTY"
                        )
                    )
                else:
                    print(f"[INFO] File '{fpath}' contains 0 statements (empty allowed).")
                continue

            all_statements.extend(stmts)

        print(f"[INFO] Total DDL statements loaded: {len(all_statements)}")
        print(f"[INFO] Mode: {'APPLY (CHANGES WILL BE PERSISTED)' if apply_changes else 'DRY-RUN (ROLLBACK AT THE END - SAFE)'}\n")

        for idx, stmt in enumerate(all_statements, 1):
            sp_name = f"sp_validate_{idx}"
            cursor.execute(f"SAVEPOINT {sp_name};")

            try:
                cursor.execute(stmt.sql)
                results.append(ValidationResult(statement=stmt, success=True))
                # In dry-run we KEEP the object alive within the transaction so dependent objects can find it
            except Exception as e:
                cursor.execute(f"ROLLBACK TO SAVEPOINT {sp_name};")
                error_msg = str(e).strip()
                pg_code = getattr(e, 'pgcode', None)
                results.append(
                    ValidationResult(
                        statement=stmt,
                        success=False,
                        error_message=error_msg,
                        pg_code=pg_code
                    )
                )

        # Perform late-binding runtime verification with plpgsql_check if available
        created_objects = [
            r.statement.object_name for r in results
            if r.success and r.statement.object_type in ('FUNCTION', 'PROCEDURE', 'TRIGGER') and r.statement.object_name != 'UNKNOWN'
        ]
        check_results, runtime_issues = check_plpgsql_runtime_validity(cursor, created_objects)
        results.extend(check_results)

        if apply_changes:
            failed_count = sum(1 for r in results if not r.success)
            if failed_count > 0:
                conn.rollback()
                print(f"\n[ERROR] {failed_count} errors encountered. Rolled back all changes to prevent partial/corrupted DDL application.")
            else:
                conn.commit()
                print("[SUCCESS] Changes committed to PostgreSQL database.")
        else:
            conn.rollback()
            print("[INFO] Test completed. Rollback executed (no changes persisted to database).")

        return results, runtime_issues
    except Exception:
        try:
            conn.rollback()
        except Exception:
            pass
        raise
    finally:
        try:
            cursor.close()
        except Exception:
            pass


def print_diagnostic_report(
    results: List[ValidationResult],
    runtime_issues: Optional[List[Tuple[str, str]]] = None
) -> bool:
    """
    Formats and prints a comprehensive diagnostic report.
    Returns True if all statements passed, False otherwise.
    """
    total = len(results)
    if total == 0:
        print("\n[ERROR] No statements found to validate.")
        return False

    passed = [r for r in results if r.success]
    failed = [r for r in results if not r.success]

    # Category counts
    by_type = {}
    for r in results:
        t = r.statement.object_type
        if t not in by_type:
            by_type[t] = {'total': 0, 'passed': 0, 'failed': 0}
        by_type[t]['total'] += 1
        if r.success:
            by_type[t]['passed'] += 1
        else:
            by_type[t]['failed'] += 1

    print("\n" + "=" * 80)
    print("           DDL VALIDATION REPORT - POSTGRESQL (LAYER 1)")
    print("=" * 80)

    print(f"\n{'OBJECT TYPE':<18} | {'TOTAL':<8} | {'SUCCESS':<10} | {'FAILED':<8} | {'RATE':<8}")
    print("-" * 65)
    for obj_type, counts in sorted(by_type.items()):
        rate = (counts['passed'] / counts['total']) * 100 if counts['total'] > 0 else 0
        print(f"{obj_type:<18} | {counts['total']:<8} | {counts['passed']:<10} | {counts['failed']:<8} | {rate:>6.1f}%")
    print("-" * 65)
    total_rate = (len(passed) / total) * 100
    print(f"{'OVERALL TOTAL':<18} | {total:<8} | {len(passed):<10} | {len(failed):<8} | {total_rate:>6.1f}%")

    if runtime_issues:
        print("\n" + "=" * 80)
        print(f"  PL/PGSQL RUNTIME CHECKER ISSUES ({len(runtime_issues)} DETECTED)")
        print("=" * 80)
        for idx, (obj_name, issue_msg) in enumerate(runtime_issues, 1):
            print(f"\n[{idx}/{len(runtime_issues)}] ⚠️  Object: {obj_name}")
            for line in issue_msg.splitlines():
                print(f"    ▶ {line}")

    if failed:
        print("\n" + "=" * 80)
        print(f"  FAILURE DETAILS ({len(failed)} OBJECTS WITH COMPILATION/CHECK ERRORS)")
        print("=" * 80)

        for idx, r in enumerate(failed, 1):
            stmt = r.statement
            print(f"\n[{idx}/{len(failed)}] ❌ {stmt.object_type}: {stmt.object_name}")
            print(f"  File: {stmt.file_name} (Line ~{stmt.start_line})")
            if r.pg_code:
                print(f"  SQLState Code: {r.pg_code}")

            # Format error message cleanly
            err_lines = r.error_message.splitlines() if r.error_message else ["Unknown error"]
            print("  PostgreSQL Error:")
            for line in err_lines[:4]:
                print(f"    ▶ {line}")

            # Show snippet of the SQL
            if stmt.sql:
                sql_snippet = "\n".join(stmt.sql.splitlines()[:6])
                if len(stmt.sql.splitlines()) > 6:
                    sql_snippet += "\n    ..."
                print("  SQL Snippet:")
                for s_line in sql_snippet.splitlines():
                    print(f"    | {s_line}")
        return False
    else:
        print("\nSUCCESS! 100% of SQL objects compiled in PostgreSQL without any errors")

        print("\n" + "-" * 80)
        print("  POSTGRESQL PL/PGSQL LATE BINDING NOTICE")
        print("  PostgreSQL validates block syntax at CREATE FUNCTION time, but embedded queries")
        print("  (column resolution, type casting, query plans) are only prepared upon first execution.")
        print("  Successful DDL compilation is necessary but not sufficient to guarantee runtime correctness.")
        print("  Run integration execution tests or install 'plpgsql_check' to verify internal query plans.")
        print("-" * 80)
        return True


def validate_postgres_ddl(
    pg_connection=None,
    target_files: Optional[List[str]] = None,
    apply_changes: bool = False,
    allow_missing_files: bool = False,
    allow_empty_files: bool = False
) -> bool:
    """
    Validates the generated PostgreSQL DDL files against a PostgreSQL instance.
    If no connection is provided, it connects using the .env configuration and closes it afterwards.
    External connections passed in by the caller remain open and under caller responsibility.
    Diagnostic preparation occurs before commit; errors in presentation do not claim rollback.
    """
    close_connection = False
    if target_files is None:
        target_files = DEFAULT_TARGET_FILES

    if pg_connection is None:
        cfg = PostgresConfig()
        print(f"\n[INFO] Connecting to PostgreSQL at '{cfg.host}:{cfg.port}/{cfg.dbname}'...")
        try:
            pg_connection = get_postgres_connection(cfg)
            close_connection = True
        except Exception as e:
            print(f"[FATAL ERROR] Could not connect to PostgreSQL: {e}")
            return False

    committed = False
    results = []
    runtime_issues = []
    try:
        results, runtime_issues = run_ddl_validation(
            conn=pg_connection,
            target_files=target_files,
            apply_changes=apply_changes,
            allow_missing_files=allow_missing_files,
            allow_empty_files=allow_empty_files
        )
        committed = apply_changes and all(r.success for r in results)
    except Exception as e:
        print(f"[FATAL ERROR] DDL validation failed during execution/preparation: {e}")
        return False
    finally:
        if close_connection and pg_connection is not None:
            try:
                pg_connection.close()
            except Exception:
                pass

    try:
        return print_diagnostic_report(results, runtime_issues=runtime_issues)
    except Exception as e:
        if committed:
            print(f"[ERROR] Failed to display diagnostic report: {e}. Note: changes WERE committed to the database.")
        else:
            print(f"[ERROR] Failed to display diagnostic report: {e}. Note: changes were NOT committed (rolled back).")
        return False


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description="Validate PostgreSQL DDL compilation and runtime correctness.")
    parser.add_argument('--apply', action='store_true', help="Persist DDL changes to database if validation passes.")
    parser.add_argument('--files', nargs='*', help="Target SQL files to validate.")
    parser.add_argument('--allow-missing', action='store_true', help="Allow missing target files without failing validation.")
    parser.add_argument('--allow-empty', action='store_true', help="Allow empty target files without failing validation.")
    cli_args = parser.parse_args()

    success = validate_postgres_ddl(
        target_files=cli_args.files if cli_args.files else None,
        apply_changes=cli_args.apply,
        allow_missing_files=cli_args.allow_missing,
        allow_empty_files=cli_args.allow_empty
    )
    if not success:
        sys.exit(1)
