"""
Validates the DDL syntax of converted PostgreSQL domains, views, functions/procedures, and triggers
against a live PostgreSQL database without making permanent changes (Dry-Run by default).
"""
import os
import re
import sys
from dataclasses import dataclass
from typing import List, Optional, Tuple

import psycopg2

from config import get_postgres_connection, PostgresConfig, get_dump_path, DumpFiles
from utils import split_sql_statements as split_sql_content

DEFAULT_TARGET_FILES = [
    get_dump_path(DumpFiles.DOMAINS_PG),
    get_dump_path(DumpFiles.VIEWS_PG),
    get_dump_path(DumpFiles.PROCEDURES_PG),
    get_dump_path(DumpFiles.TRIGGERS_PG)
]


@dataclass
class SQLStatement:
    file_name: str
    object_type: str  # 'DOMAIN', 'VIEW', 'FUNCTION', 'TRIGGER', 'OTHER'
    object_name: str
    sql: str
    start_line: int


@dataclass
class ValidationResult:
    statement: SQLStatement
    success: bool
    error_message: Optional[str] = None
    pg_code: Optional[str] = None


def split_sql_statements(file_path: str, allow_missing: bool = False) -> List[SQLStatement]:
    """
    Parses a PostgreSQL SQL file into individual SQLStatement objects.
    The low-level splitting (quotes, comments, dollar-quoting) lives in sql_splitter.
    """
    if not os.path.exists(file_path):
        if not allow_missing:
            raise FileNotFoundError(f"Target SQL file '{file_path}' not found.")
        print(f"[WARNING] File '{file_path}' not found. Skipping.")
        return []

    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    statements = []
    for sql, start_line in split_sql_content(content):
        obj_type, obj_name = identify_object(sql)
        statements.append(
            SQLStatement(
                file_name=os.path.basename(file_path),
                object_type=obj_type,
                object_name=obj_name,
                sql=sql,
                start_line=start_line
            )
        )

    return statements


def identify_object(sql_text: str) -> Tuple[str, str]:
    """
    Identifies the SQL object type and name from statement text.
    """
    clean_sql = re.sub(r'--[^\n]*\n', '\n', sql_text)
    clean_sql = re.sub(r'/\*.*?\*/', '', clean_sql, flags=re.DOTALL).strip()

    # Domain: schema-qualified quoted form (generated by DdlExporter, possibly nested in a
    # DO block), plain quoted form, or bare unquoted form
    m = (re.search(r'CREATE\s+DOMAIN\s+(?:[a-zA-Z0-9_]+\.)?"([^"]+)"', clean_sql, re.IGNORECASE)
         or re.search(r'CREATE\s+DOMAIN\s+([a-zA-Z0-9_]+)', clean_sql, re.IGNORECASE))
    if m:
        return 'DOMAIN', m.group(1)

    # View
    m = re.search(r'CREATE\s+(?:OR\s+REPLACE\s+)?VIEW\s+"?([a-zA-Z0-9_]+)"?', clean_sql, re.IGNORECASE)
    if m:
        return 'VIEW', m.group(1)

    # Function
    m = re.search(r'CREATE\s+(?:OR\s+REPLACE\s+)?FUNCTION\s+"?([a-zA-Z0-9_]+)"?\s*\(', clean_sql, re.IGNORECASE)
    if m:
        return 'FUNCTION', m.group(1)

    # Procedure
    m = re.search(r'CREATE\s+(?:OR\s+REPLACE\s+)?PROCEDURE\s+"?([a-zA-Z0-9_]+)"?\s*\(', clean_sql, re.IGNORECASE)
    if m:
        return 'PROCEDURE', m.group(1)

    # Trigger
    m = re.search(r'CREATE\s+TRIGGER\s+"?([a-zA-Z0-9_]+)"?\s+', clean_sql, re.IGNORECASE)
    if m:
        return 'TRIGGER', m.group(1)

    return 'OTHER', 'UNKNOWN'


# Status constants for PL/pgSQL runtime verification
CHECK_PASSED = "PASSED"                    # "verificado sem erros"
CHECK_ISSUES_FOUND = "ISSUES_FOUND"        # "problemas encontrados"
CHECK_NOT_PERFORMED = "NOT_PERFORMED"      # "não foi possível verificar / verificação não realizada"


def check_plpgsql_runtime_validity(
    cursor,
    function_names: Optional[List[str]] = None,
    require_checker: bool = False
) -> tuple[List[ValidationResult], List[tuple[str, str]], str]:
    """
    Checks PL/pgSQL functions and triggers for runtime syntax and column/type errors
    using plpgsql_check_function_tb with proper OIDs and trigger relation IDs.
    Wraps each check and catalog query in a SAVEPOINT to preserve transaction state.
    Distinguishes:
      - 'PASSED' (verificado sem erros)
      - 'ISSUES_FOUND' (problemas encontrados)
      - 'NOT_PERFORMED' (não foi possível verificar / verificação não realizada)

    Returns (validation_results, runtime_issues, checker_status).
    """
    validation_results: List[ValidationResult] = []
    runtime_issues: List[tuple[str, str]] = []

    # 1. Extension presence check wrapped in SAVEPOINT
    try:
        cursor.execute("SAVEPOINT sp_check_ext;")
        cursor.execute("SELECT 1 FROM pg_extension WHERE extname = 'plpgsql_check';")
        row = cursor.fetchone()
        has_ext = bool(row and row[0] == 1)
        cursor.execute("RELEASE SAVEPOINT sp_check_ext;")
    except psycopg2.Error:
        try:
            cursor.execute("ROLLBACK TO SAVEPOINT sp_check_ext;")
        except psycopg2.Error:
            pass
        has_ext = False

    if not has_ext:
        if require_checker:
            validation_results.append(
                ValidationResult(
                    statement=SQLStatement(
                        file_name="extension",
                        object_type="EXTENSION",
                        object_name="plpgsql_check",
                        sql="CREATE EXTENSION plpgsql_check;",
                        start_line=0
                    ),
                    success=False,
                    error_message=(
                        "Runtime checking is required (require_checker=True), "
                        "but the 'plpgsql_check' extension is not installed or available."
                    ),
                    pg_code="CHECKER_REQUIRED"
                )
            )
            runtime_issues.append((
                "plpgsql_check",
                "[verificação não realizada] Extensão 'plpgsql_check' ausente, mas verificação runtime é obrigatória."
            ))
        else:
            runtime_issues.append((
                "plpgsql_check",
                "[verificação não realizada] Extensão 'plpgsql_check' ausente no banco de dados."
            ))
        return validation_results, runtime_issues, CHECK_NOT_PERFORMED

    filter_names = set(n.lower() for n in function_names) if function_names is not None else None
    discovery_failed = False

    # 2. Inspect regular functions & procedures with overload signatures and OIDs
    regular_funcs = []
    try:
        cursor.execute("SAVEPOINT sp_discover_funcs;")
        cursor.execute("""
            SELECT p.oid, p.proname, n.nspname,
                   pg_get_function_identity_arguments(p.oid) AS identity_args
            FROM pg_proc p
            JOIN pg_namespace n ON n.oid = p.pronamespace
            WHERE (n.nspname = ANY(current_schemas(false)) OR n.nspname = 'public')
              AND p.prolang = (SELECT oid FROM pg_language WHERE lanname = 'plpgsql')
              AND p.prorettype <> (SELECT oid FROM pg_type WHERE typname = 'trigger')
            ORDER BY p.oid;
        """)
        regular_funcs = cursor.fetchall()
        cursor.execute("RELEASE SAVEPOINT sp_discover_funcs;")
    except Exception as e:
        try:
            cursor.execute("ROLLBACK TO SAVEPOINT sp_discover_funcs;")
        except psycopg2.Error:
            pass
        err_msg = str(e).strip()
        validation_results.append(
            ValidationResult(
                statement=SQLStatement(
                    file_name="catalog",
                    object_type="CATALOG",
                    object_name="pg_proc",
                    sql="SELECT p.oid, p.proname FROM pg_proc ...",
                    start_line=0
                ),
                success=False,
                error_message=f"Falha na descoberta de funções/procedimentos PL/pgSQL no catálogo: {err_msg}",
                pg_code=getattr(e, 'pgcode', 'CATALOG_DISCOVERY_FAILED')
            )
        )
        runtime_issues.append(("catalog", f"[falha de descoberta de funções] {err_msg}"))
        discovery_failed = True

    # 3. Inspect trigger functions with their target relation IDs
    triggers = []
    try:
        cursor.execute("SAVEPOINT sp_discover_triggers;")
        cursor.execute("""
            SELECT t.tgfoid, p.proname, t.tgrelid, c.relname, t.tgname, n.nspname
            FROM pg_trigger t
            JOIN pg_proc p ON p.oid = t.tgfoid
            JOIN pg_class c ON c.oid = t.tgrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE (n.nspname = ANY(current_schemas(false)) OR n.nspname = 'public')
              AND NOT t.tgisinternal
            ORDER BY t.tgfoid, t.tgrelid;
        """)
        triggers = cursor.fetchall()
        cursor.execute("RELEASE SAVEPOINT sp_discover_triggers;")
    except Exception as e:
        try:
            cursor.execute("ROLLBACK TO SAVEPOINT sp_discover_triggers;")
        except psycopg2.Error:
            pass
        err_msg = str(e).strip()
        validation_results.append(
            ValidationResult(
                statement=SQLStatement(
                    file_name="catalog",
                    object_type="CATALOG",
                    object_name="pg_trigger",
                    sql="SELECT t.tgfoid ... FROM pg_trigger ...",
                    start_line=0
                ),
                success=False,
                error_message=f"Falha na descoberta de triggers PL/pgSQL no catálogo: {err_msg}",
                pg_code=getattr(e, 'pgcode', 'CATALOG_DISCOVERY_FAILED')
            )
        )
        runtime_issues.append(("catalog", f"[falha de descoberta de triggers] {err_msg}"))
        discovery_failed = True

    if discovery_failed:
        return validation_results, runtime_issues, CHECK_NOT_PERFORMED

    check_targets = []
    for fn_oid, fn_name, nsp, identity_args in regular_funcs:
        full_sig = f"{fn_name}({identity_args})" if identity_args else fn_name
        if filter_names is None or fn_name.lower() in filter_names or full_sig.lower() in filter_names:
            check_targets.append((fn_oid, 0, full_sig, 'FUNCTION'))

    for tg_foid, fn_name, tg_relid, rel_name, tg_name, nsp in triggers:
        if filter_names is None or fn_name.lower() in filter_names or tg_name.lower() in filter_names or rel_name.lower() in filter_names:
            check_targets.append((tg_foid, tg_relid, f"{tg_name} on {rel_name}", 'TRIGGER'))

    has_errors = False
    for idx, (f_oid, r_oid, obj_name, obj_type) in enumerate(check_targets, 1):
        sp_name = f"sp_plpgsql_check_{idx}"
        try:
            cursor.execute(f"SAVEPOINT {sp_name};")
            cursor.execute(
                "SELECT message, level, sqlstate, lineno, statement FROM plpgsql_check_function_tb(%s, %s);",
                (f_oid, r_oid)
            )
            rows = cursor.fetchall()
            cursor.execute(f"RELEASE SAVEPOINT {sp_name};")

            for msg, level, sqlstate, lineno, stmt_text in rows:
                lvl_str = str(level).lower()
                desc = f"[{level}] {msg} (line {lineno})" if lineno else f"[{level}] {msg}"
                runtime_issues.append((obj_name, desc))
                if lvl_str in ('error', 'fatal'):
                    has_errors = True
                    validation_results.append(
                        ValidationResult(
                            statement=SQLStatement(
                                sql=stmt_text or f"-- plpgsql_check {obj_name}",
                                file_name="plpgsql_check",
                                start_line=lineno or 0,
                                object_type=obj_type,
                                object_name=obj_name
                            ),
                            success=False,
                            error_message=f"[plpgsql_check {lvl_str}] {msg}" + (f" (line {lineno})" if lineno else ""),
                            pg_code=sqlstate
                        )
                    )
        except Exception as e:
            try:
                cursor.execute(f"ROLLBACK TO SAVEPOINT {sp_name};")
            except psycopg2.Error:
                pass
            err_msg = str(e).strip()
            has_errors = True
            runtime_issues.append((obj_name, f"[check exception] {err_msg}"))
            validation_results.append(
                ValidationResult(
                    statement=SQLStatement(
                        sql=f"-- plpgsql_check exception on {obj_name}",
                        file_name="plpgsql_check",
                        start_line=0,
                        object_type=obj_type,
                        object_name=obj_name
                    ),
                    success=False,
                    error_message=f"[plpgsql_check exception] {err_msg}",
                    pg_code=getattr(e, 'pgcode', 'CHECKER_EXCEPTION')
                )
            )

    if has_errors:
        status = CHECK_ISSUES_FOUND
    elif runtime_issues:
        status = CHECK_ISSUES_FOUND
    else:
        status = CHECK_PASSED

    return validation_results, runtime_issues, status


def run_ddl_validation(
    conn,
    target_files: List[str],
    apply_changes: bool = False,
    allow_missing_files: bool = False,
    allow_empty_files: bool = False,
    require_checker: bool = False
) -> tuple[List[ValidationResult], List[tuple[str, str]], str]:
    """
    Executes each statement in sequence inside a PostgreSQL transaction using SAVEPOINTS.
    In dry-run mode (default), the entire transaction is rolled back at the end.
    Returns (results, runtime_issues, checker_status).
    """
    if getattr(conn, 'autocommit', False):
        conn.autocommit = False
    cursor = conn.cursor()
    try:
        results: List[ValidationResult] = []
        all_statements: List[SQLStatement] = []
        for fpath in target_files:
            if not os.path.exists(fpath):
                if not allow_missing_files:
                    results.append(
                        ValidationResult(
                            statement=SQLStatement(
                                file_name=os.path.basename(fpath),
                                object_type="FILE",
                                object_name=fpath,
                                sql="",
                                start_line=0
                            ),
                            success=False,
                            error_message=f"Target file not found: '{fpath}'",
                            pg_code="FILE_NOT_FOUND"
                        )
                    )
                else:
                    print(f"[WARNING] File '{fpath}' not found. Skipping.")
                continue

            stmts = split_sql_statements(fpath, allow_missing=True)
            if not stmts:
                if not allow_empty_files:
                    results.append(
                        ValidationResult(
                            statement=SQLStatement(
                                file_name=os.path.basename(fpath),
                                object_type="FILE",
                                object_name=fpath,
                                sql="",
                                start_line=0
                            ),
                            success=False,
                            error_message=f"Target file '{fpath}' contains 0 SQL statements (empty file). Set allow_empty_files=True if permitted.",
                            pg_code="FILE_EMPTY"
                        )
                    )
                else:
                    print(f"[INFO] File '{fpath}' contains 0 statements (empty allowed).")
                continue

            all_statements.extend(stmts)

        print(f"[INFO] Total DDL statements loaded: {len(all_statements)}")
        print(f"[INFO] Mode: {'APPLY (CHANGES WILL BE PERSISTED)' if apply_changes else 'DRY-RUN (ROLLBACK AT THE END - SAFE)'}\n")

        for idx, stmt in enumerate(all_statements, 1):
            sp_name = f"sp_validate_{idx}"
            cursor.execute(f"SAVEPOINT {sp_name};")

            try:
                cursor.execute(stmt.sql)
                results.append(ValidationResult(statement=stmt, success=True))
                # In dry-run we KEEP the object alive within the transaction so dependent objects can find it
            except Exception as e:
                cursor.execute(f"ROLLBACK TO SAVEPOINT {sp_name};")
                error_msg = str(e).strip()
                pg_code = getattr(e, 'pgcode', None)
                results.append(
                    ValidationResult(
                        statement=stmt,
                        success=False,
                        error_message=error_msg,
                        pg_code=pg_code
                    )
                )

        # Determine target objects for PL/pgSQL runtime verification
        created_objects = [
            r.statement.object_name for r in results
            if r.success and r.statement.object_type in ('FUNCTION', 'PROCEDURE', 'TRIGGER') and r.statement.object_name != 'UNKNOWN'
        ]

        check_results, runtime_issues, checker_status = check_plpgsql_runtime_validity(
            cursor,
            function_names=created_objects,
            require_checker=require_checker
        )
        results.extend(check_results)

        if apply_changes:
            failed_count = sum(1 for r in results if not r.success)
            if failed_count > 0:
                conn.rollback()
                print(f"\n[ERROR] {failed_count} errors encountered. Rolled back all changes to prevent partial/corrupted DDL application.")
            else:
                conn.commit()
                print("[SUCCESS] Changes committed to PostgreSQL database.")
        else:
            conn.rollback()
            print("[INFO] Test completed. Rollback executed (no changes persisted to database).")

        return results, runtime_issues, checker_status
    except Exception:
        try:
            conn.rollback()
        except psycopg2.Error:
            pass
        raise
    finally:
        try:
            cursor.close()
        except psycopg2.Error:
            pass


def print_diagnostic_report(
    results: List[ValidationResult],
    runtime_issues: Optional[List[Tuple[str, str]]] = None,
    checker_status: Optional[str] = None
) -> bool:
    """
    Formats and prints a comprehensive diagnostic report.
    Returns True if all statements passed, False otherwise.
    """
    total = len(results)
    if total == 0:
        print("\n[ERROR] No statements found to validate.")
        return False

    passed = [r for r in results if r.success]
    failed = [r for r in results if not r.success]

    # Category counts
    by_type = {}
    for r in results:
        t = r.statement.object_type
        if t not in by_type:
            by_type[t] = {'total': 0, 'passed': 0, 'failed': 0}
        by_type[t]['total'] += 1
        if r.success:
            by_type[t]['passed'] += 1
        else:
            by_type[t]['failed'] += 1

    print("\n" + "=" * 80)
    print("           DDL VALIDATION REPORT - POSTGRESQL (LAYER 1)")
    print("=" * 80)

    print(f"\n{'OBJECT TYPE':<18} | {'TOTAL':<8} | {'SUCCESS':<10} | {'FAILED':<8} | {'RATE':<8}")
    print("-" * 65)
    for obj_type, counts in sorted(by_type.items()):
        rate = (counts['passed'] / counts['total']) * 100 if counts['total'] > 0 else 0
        print(f"{obj_type:<18} | {counts['total']:<8} | {counts['passed']:<10} | {counts['failed']:<8} | {rate:>6.1f}%")
    print("-" * 65)
    total_rate = (len(passed) / total) * 100
    print(f"{'OVERALL TOTAL':<18} | {total:<8} | {len(passed):<10} | {len(failed):<8} | {total_rate:>6.1f}%")

    # Section for PL/pgSQL Runtime Checker status
    if checker_status or runtime_issues:
        print("\n" + "=" * 80)
        print("  PL/PGSQL RUNTIME VERIFICATION (plpgsql_check)")
        print("=" * 80)
        if checker_status == CHECK_PASSED:
            print("  Status: VERIFICADO SEM ERROS")
            print("  All PL/pgSQL functions and triggers verified without query plan or semantic issues.")
        elif checker_status == CHECK_ISSUES_FOUND:
            print("  Status: PROBLEMAS ENCONTRADOS")
            print(f"  {len(runtime_issues or [])} issue(s) detected during PL/pgSQL runtime checks.")
        elif checker_status == CHECK_NOT_PERFORMED:
            print("  Status: NÃO FOI POSSÍVEL VERIFICAR (VERIFICAÇÃO NÃO REALIZADA)")
            print("  plpgsql_check extension is not available or catalog discovery failed.")
        elif runtime_issues:
            print(f"  Status: PROBLEMAS ENCONTRADOS ({len(runtime_issues)} issues)")

        if runtime_issues:
            for idx, (obj_name, issue_msg) in enumerate(runtime_issues, 1):
                print(f"\n[{idx}/{len(runtime_issues)}] ⚠️  Object: {obj_name}")
                for line in issue_msg.splitlines():
                    print(f"    ▶ {line}")

    if failed:
        print("\n" + "=" * 80)
        print(f"  FAILURE DETAILS ({len(failed)} OBJECTS WITH COMPILATION/CHECK ERRORS)")
        print("=" * 80)

        for idx, r in enumerate(failed, 1):
            stmt = r.statement
            print(f"\n[{idx}/{len(failed)}] ❌ {stmt.object_type}: {stmt.object_name}")
            print(f"  File: {stmt.file_name} (Line ~{stmt.start_line})")
            if r.pg_code:
                print(f"  SQLState Code: {r.pg_code}")

            # Format error message cleanly
            err_lines = r.error_message.splitlines() if r.error_message else ["Unknown error"]
            print("  PostgreSQL Error:")
            for line in err_lines[:4]:
                print(f"    ▶ {line}")

            # Show snippet of the SQL
            if stmt.sql:
                sql_snippet = "\n".join(stmt.sql.splitlines()[:6])
                if len(stmt.sql.splitlines()) > 6:
                    sql_snippet += "\n    ..."
                print("  SQL Snippet:")
                for s_line in sql_snippet.splitlines():
                    print(f"    | {s_line}")
        return False
    else:
        print("\nSUCCESS! 100% of SQL objects compiled in PostgreSQL without any errors")

        print("\n" + "-" * 80)
        print("  POSTGRESQL PL/PGSQL LATE BINDING NOTICE")
        print("  PostgreSQL validates block syntax at CREATE FUNCTION time, but embedded queries")
        print("  (column resolution, type casting, query plans) are only prepared upon first execution.")
        print("  Successful DDL compilation is necessary but not sufficient to guarantee runtime correctness.")
        print("  Run integration execution tests or install 'plpgsql_check' to verify internal query plans.")
        print("-" * 80)
        return True


def validate_postgres_ddl(
    pg_connection=None,
    target_files: Optional[List[str]] = None,
    apply_changes: bool = False,
    allow_missing_files: bool = False,
    allow_empty_files: bool = False,
    require_checker: bool = False
) -> bool:
    """
    Validates the generated PostgreSQL DDL files against a PostgreSQL instance.
    If no connection is provided, it connects using the .env configuration and closes it afterwards.
    External connections passed in by the caller remain open and under caller responsibility.
    Diagnostic preparation occurs before commit; errors in presentation do not claim rollback.
    """
    close_connection = False
    if target_files is None:
        target_files = DEFAULT_TARGET_FILES

    if pg_connection is None:
        cfg = PostgresConfig()
        print(f"\n[INFO] Connecting to PostgreSQL at '{cfg.host}:{cfg.port}/{cfg.dbname}'...")
        try:
            pg_connection = get_postgres_connection(cfg)
            close_connection = True
        except Exception as e:
            print(f"[FATAL ERROR] Could not connect to PostgreSQL: {e}")
            return False

    committed = False
    results = []
    runtime_issues = []
    checker_status = CHECK_NOT_PERFORMED
    try:
        results, runtime_issues, checker_status = run_ddl_validation(
            conn=pg_connection,
            target_files=target_files,
            apply_changes=apply_changes,
            allow_missing_files=allow_missing_files,
            allow_empty_files=allow_empty_files,
            require_checker=require_checker
        )
        committed = apply_changes and all(r.success for r in results)
    except Exception as e:
        print(f"[FATAL ERROR] DDL validation failed during execution/preparation: {e}")
        return False
    finally:
        if close_connection and pg_connection is not None:
            try:
                pg_connection.close()
            except psycopg2.Error:
                pass

    try:
        return print_diagnostic_report(results, runtime_issues=runtime_issues, checker_status=checker_status)
    except Exception as e:
        if committed:
            print(f"[ERROR] Failed to display diagnostic report: {e}. Note: changes WERE committed to the database.")
        else:
            print(f"[ERROR] Failed to display diagnostic report: {e}. Note: changes were NOT committed (rolled back).")
        return False


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description="Validate PostgreSQL DDL compilation and runtime correctness.")
    parser.add_argument('--apply', action='store_true', help="Persist DDL changes to database if validation passes.")
    parser.add_argument('--files', nargs='*', help="Target SQL files to validate.")
    parser.add_argument('--allow-missing', action='store_true', help="Allow missing target files without failing validation.")
    parser.add_argument('--allow-empty', action='store_true', help="Allow empty target files without failing validation.")
    parser.add_argument('--require-checker', action='store_true', help="Require plpgsql_check validation to pass. Fails if extension is missing.")
    cli_args = parser.parse_args()

    success = validate_postgres_ddl(
        target_files=cli_args.files if cli_args.files else None,
        apply_changes=cli_args.apply,
        allow_missing_files=cli_args.allow_missing,
        allow_empty_files=cli_args.allow_empty,
        require_checker=cli_args.require_checker
    )
    if not success:
        sys.exit(1)
