import unittest

from validate_postgres_ddl import identify_object


class TestIdentifyObject(unittest.TestCase):
    def test_domain_schema_qualified_quoted_in_do_block(self):
        # Format generated by DdlExporter: DO block wrapping the CREATE DOMAIN
        sql = (
            'DO $$\n'
            'BEGIN\n'
            "    IF NOT EXISTS (SELECT 1 FROM pg_type t) THEN\n"
            "        EXECUTE 'CREATE DOMAIN public.\"varchar20\" AS VARCHAR(20);';\n"
            '    END IF;\n'
            'END $$;'
        )
        self.assertEqual(identify_object(sql), ('DOMAIN', 'varchar20'))

    def test_domain_plain_quoted(self):
        self.assertEqual(identify_object('CREATE DOMAIN "meu_dominio" AS INTEGER;'),
                         ('DOMAIN', 'meu_dominio'))

    def test_domain_bare_unquoted(self):
        self.assertEqual(identify_object('CREATE DOMAIN MEU_DOMINIO AS INTEGER;'),
                         ('DOMAIN', 'MEU_DOMINIO'))

    def test_domain_with_hyphen(self):
        self.assertEqual(identify_object("CREATE DOMAIN public.\"e-mail\" AS VARCHAR(50);"),
                         ('DOMAIN', 'e-mail'))

    def test_view(self):
        self.assertEqual(
            identify_object('DROP VIEW IF EXISTS "MINHA_VIEW" CASCADE;\nCREATE VIEW "MINHA_VIEW" AS SELECT 1;'),
            ('VIEW', 'MINHA_VIEW'))

    def test_function(self):
        sql = ('CREATE FUNCTION "minha_func"() RETURNS void AS $$\n'
               'BEGIN\n'
               'END;\n'
               '$$ LANGUAGE plpgsql;')
        self.assertEqual(identify_object(sql), ('FUNCTION', 'minha_func'))

    def test_trigger(self):
        self.assertEqual(
            identify_object('DROP TRIGGER IF EXISTS "TRG_X" ON "tabela";\n'
                            'CREATE TRIGGER "TRG_X" BEFORE INSERT ON "tabela" FOR EACH ROW EXECUTE FUNCTION f();'),
            ('TRIGGER', 'TRG_X'))

    def test_other_statement(self):
        self.assertEqual(identify_object('SELECT 1;'), ('OTHER', 'UNKNOWN'))


class TestRunDdlValidation(unittest.TestCase):
    def test_apply_changes_rolls_back_when_any_statement_fails(self):
        import tempfile
        from unittest.mock import MagicMock
        from validate_postgres_ddl import run_ddl_validation

        with tempfile.NamedTemporaryFile('w', suffix='.sql', delete=False) as f:
            f.write('DROP VIEW IF EXISTS "v" CASCADE;\nCREATE VIEW "v" AS INVALID_SYNTAX;\n')
            fpath = f.name

        try:
            mock_conn = MagicMock()
            mock_cursor = MagicMock()
            mock_conn.cursor.return_value = mock_cursor

            # First statement succeeds, second fails
            def execute_side_effect(sql):
                if 'INVALID_SYNTAX' in sql:
                    raise Exception("syntax error at or near 'INVALID_SYNTAX'")

            mock_cursor.execute.side_effect = execute_side_effect

            results, _ = run_ddl_validation(mock_conn, [fpath], apply_changes=True)
            self.assertEqual(len(results), 2)
            self.assertTrue(results[0].success)
            self.assertFalse(results[1].success)

            mock_conn.rollback.assert_called()
            mock_conn.commit.assert_not_called()
        finally:
            import os
            os.remove(fpath)

    def test_apply_changes_commits_when_all_statements_succeed(self):
        import tempfile
        from unittest.mock import MagicMock
        from validate_postgres_ddl import run_ddl_validation

        with tempfile.NamedTemporaryFile('w', suffix='.sql', delete=False) as f:
            f.write('SELECT 1;\nSELECT 2;\n')
            fpath = f.name

        try:
            mock_conn = MagicMock()
            mock_cursor = MagicMock()
            mock_conn.cursor.return_value = mock_cursor

            results, _ = run_ddl_validation(mock_conn, [fpath], apply_changes=True)
            self.assertEqual(len(results), 2)
            self.assertTrue(all(r.success for r in results))

            mock_conn.commit.assert_called_once()
        finally:
            import os
            os.remove(fpath)

    def test_run_ddl_validation_safe_against_strict_connection_and_ensures_cleanup(self):
        import tempfile
        from unittest.mock import MagicMock
        from validate_postgres_ddl import run_ddl_validation

        with tempfile.NamedTemporaryFile('w', suffix='.sql', delete=False) as f:
            f.write('SELECT 1;\n')
            fpath = f.name

        try:
            # Emulate real C extension connection that rejects arbitrary attribute assignment
            class StrictConnection:
                def __init__(self, cursor):
                    self.autocommit = False
                    self._cursor = cursor
                    self.rolled_back = False
                    self.committed = False

                def cursor(self):
                    return self._cursor

                def rollback(self):
                    self.rolled_back = True

                def commit(self):
                    self.committed = True

                def __setattr__(self, name, value):
                    if name in ('autocommit', '_cursor', 'rolled_back', 'committed'):
                        super().__setattr__(name, value)
                    else:
                        raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")

            mock_cursor = MagicMock()
            strict_conn = StrictConnection(mock_cursor)

            results, runtime_issues = run_ddl_validation(strict_conn, [fpath], apply_changes=False)
            self.assertEqual(len(results), 1)
            self.assertTrue(results[0].success)
            self.assertTrue(strict_conn.rolled_back)
            mock_cursor.close.assert_called_once()
        finally:
            import os
            os.remove(fpath)

    def test_print_diagnostic_report_empty_returns_false(self):
        from validate_postgres_ddl import print_diagnostic_report
        self.assertFalse(print_diagnostic_report([]))


if __name__ == '__main__':
    unittest.main()
