import unittest

import psycopg2

from tests.db_isolation import (
    get_test_postgres_connection,
    require_live_postgres,
    requires_postgres_class,
    unique_name,
)
from validate_postgres_ddl import identify_object


class TestIdentifyObject(unittest.TestCase):
    def test_domain_schema_qualified_quoted_in_do_block(self):
        # Format generated by DdlExporter: DO block wrapping the CREATE DOMAIN
        sql = (
            'DO $$\n'
            'BEGIN\n'
            "    IF NOT EXISTS (SELECT 1 FROM pg_type t) THEN\n"
            "        EXECUTE 'CREATE DOMAIN public.\"varchar20\" AS VARCHAR(20);';\n"
            '    END IF;\n'
            'END $$;'
        )
        self.assertEqual(identify_object(sql), ('DOMAIN', 'varchar20'))

    def test_domain_plain_quoted(self):
        self.assertEqual(identify_object('CREATE DOMAIN "meu_dominio" AS INTEGER;'),
                         ('DOMAIN', 'meu_dominio'))

    def test_domain_bare_unquoted(self):
        self.assertEqual(identify_object('CREATE DOMAIN MEU_DOMINIO AS INTEGER;'),
                         ('DOMAIN', 'MEU_DOMINIO'))

    def test_domain_with_hyphen(self):
        self.assertEqual(identify_object("CREATE DOMAIN public.\"e-mail\" AS VARCHAR(50);"),
                         ('DOMAIN', 'e-mail'))

    def test_view(self):
        self.assertEqual(
            identify_object('DROP VIEW IF EXISTS "MINHA_VIEW" CASCADE;\nCREATE VIEW "MINHA_VIEW" AS SELECT 1;'),
            ('VIEW', 'MINHA_VIEW'))

    def test_function(self):
        sql = ('CREATE FUNCTION "minha_func"() RETURNS void AS $$\n'
               'BEGIN\n'
               'END;\n'
               '$$ LANGUAGE plpgsql;')
        self.assertEqual(identify_object(sql), ('FUNCTION', 'minha_func'))

    def test_trigger(self):
        self.assertEqual(
            identify_object('DROP TRIGGER IF EXISTS "TRG_X" ON "tabela";\n'
                            'CREATE TRIGGER "TRG_X" BEFORE INSERT ON "tabela" FOR EACH ROW EXECUTE FUNCTION f();'),
            ('TRIGGER', 'TRG_X'))

    def test_function_with_hyphen_and_space(self):
        self.assertEqual(
            identify_object('CREATE FUNCTION "p-with-dash"() RETURNS void AS $$ BEGIN END; $$ LANGUAGE plpgsql;'),
            ('FUNCTION', 'p-with-dash')
        )
        self.assertEqual(
            identify_object('CREATE OR REPLACE FUNCTION "func with spaces"() RETURNS void AS $$ BEGIN END; $$ LANGUAGE plpgsql;'),
            ('FUNCTION', 'func with spaces')
        )
        self.assertEqual(
            identify_object('CREATE FUNCTION public."p-with-dash"() RETURNS void AS $$ BEGIN END; $$ LANGUAGE plpgsql;'),
            ('FUNCTION', 'p-with-dash')
        )

    def test_procedure_with_hyphen(self):
        self.assertEqual(
            identify_object('CREATE PROCEDURE "p-with-dash"() AS $$ BEGIN END; $$ LANGUAGE plpgsql;'),
            ('PROCEDURE', 'p-with-dash')
        )

    def test_view_and_trigger_with_hyphen(self):
        self.assertEqual(
            identify_object('CREATE VIEW "v-with-dash" AS SELECT 1;'),
            ('VIEW', 'v-with-dash')
        )
        self.assertEqual(
            identify_object('CREATE TRIGGER "trg-with-dash" BEFORE INSERT ON "table" FOR EACH ROW EXECUTE FUNCTION f();'),
            ('TRIGGER', 'trg-with-dash')
        )

    def test_other_statement(self):
        self.assertEqual(identify_object('SELECT 1;'), ('OTHER', 'UNKNOWN'))

    def test_function_containing_create_domain_message_is_function(self):
        """
        P1 regression: RAISE NOTICE 'CREATE DOMAIN fake ...' inside a function
        body is text, not a definition. The effectively executed command is
        CREATE FUNCTION, so the statement must identify as FUNCTION (never
        DOMAIN fake), keeping it a plpgsql_check target.
        """
        sql = (
            'CREATE FUNCTION "f_msg"() RETURNS void AS $$\n'
            'BEGIN\n'
            "    RAISE NOTICE 'CREATE DOMAIN fake AS integer';\n"
            '    PERFORM * FROM nonexistent_table;\n'
            'END;\n'
            '$$ LANGUAGE plpgsql;'
        )
        self.assertEqual(identify_object(sql), ('FUNCTION', 'f_msg'))

    def test_function_message_with_escaped_quotes_and_comments(self):
        """
        P1 regression: escaped quotes and comment markers inside the message
        literal must not fabricate objects nor corrupt the real identity.
        """
        sql = (
            'CREATE FUNCTION "f""x"() RETURNS void AS $$\n'
            'BEGIN\n'
            "    RAISE NOTICE 'say \"hi\" -- CREATE VIEW ghost_v AS SELECT 1 /* CREATE TRIGGER ghost_t */';\n"
            'END;\n'
            '$$ LANGUAGE plpgsql;'
        )
        self.assertEqual(identify_object(sql), ('FUNCTION', 'f"x'))

    def test_commented_create_is_not_identified(self):
        """A CREATE mentioned only in a real comment identifies as OTHER."""
        self.assertEqual(
            identify_object('-- CREATE FUNCTION ghost() RETURNS void;\nSELECT 1;'),
            ('OTHER', 'UNKNOWN')
        )

    def test_hostile_function_name_identifies_as_single_function(self):
        """
        P1 regression: a function NAMED "CREATE DOMAIN fake" is one FUNCTION
        identity (its header), never DOMAIN fake. The name is a single
        identifier even though its content looks like a command.
        """
        sql = (
            'CREATE FUNCTION "CREATE DOMAIN fake"() RETURNS void AS $$\n'
            'BEGIN\n'
            "    RAISE NOTICE 'hi';\n"
            '    PERFORM * FROM nonexistent_table;\n'
            'END;\n'
            '$$ LANGUAGE plpgsql;'
        )
        self.assertEqual(identify_object(sql), ('FUNCTION', 'CREATE DOMAIN fake'))

    def test_hostile_names_with_comments_and_escaped_quotes(self):
        """
        P1 regression: names containing apparent comments or escaped quotes
        stay single identifiers and fabricate no extra identities.
        """
        self.assertEqual(
            identify_object('CREATE VIEW "my -- view" AS SELECT 1;'),
            ('VIEW', 'my -- view')
        )
        self.assertEqual(
            identify_object('CREATE VIEW "x /* y */ z" AS SELECT 1;'),
            ('VIEW', 'x /* y */ z')
        )
        self.assertEqual(
            identify_object('CREATE FUNCTION "CREATE FUNCTION ghost"() RETURNS void AS $$ BEGIN END; $$ LANGUAGE plpgsql;'),
            ('FUNCTION', 'CREATE FUNCTION ghost')
        )


class TestRunDdlValidation(unittest.TestCase):
    def test_apply_changes_rolls_back_when_any_statement_fails(self):
        import tempfile
        from unittest.mock import MagicMock
        from validate_postgres_ddl import run_ddl_validation

        with tempfile.NamedTemporaryFile('w', suffix='.sql', delete=False) as f:
            f.write('DROP VIEW IF EXISTS "v" CASCADE;\nCREATE VIEW "v" AS INVALID_SYNTAX;\n')
            fpath = f.name

        try:
            mock_conn = MagicMock()
            mock_cursor = MagicMock()
            mock_conn.cursor.return_value = mock_cursor

            # First statement succeeds, second fails
            def execute_side_effect(sql):
                if 'INVALID_SYNTAX' in sql:
                    raise Exception("syntax error at or near 'INVALID_SYNTAX'")

            mock_cursor.execute.side_effect = execute_side_effect

            results, *_ = run_ddl_validation(mock_conn, [fpath], apply_changes=True)
            self.assertEqual(len(results), 2)
            self.assertTrue(results[0].success)
            self.assertFalse(results[1].success)

            mock_conn.rollback.assert_called()
            mock_conn.commit.assert_not_called()
        finally:
            import os
            os.remove(fpath)

    def test_apply_changes_commits_when_all_statements_succeed(self):
        import tempfile
        from unittest.mock import MagicMock
        from validate_postgres_ddl import run_ddl_validation

        with tempfile.NamedTemporaryFile('w', suffix='.sql', delete=False) as f:
            f.write('SELECT 1;\nSELECT 2;\n')
            fpath = f.name

        try:
            mock_conn = MagicMock()
            mock_cursor = MagicMock()
            mock_conn.cursor.return_value = mock_cursor

            results, *_ = run_ddl_validation(mock_conn, [fpath], apply_changes=True)
            self.assertEqual(len(results), 2)
            self.assertTrue(all(r.success for r in results))

            mock_conn.commit.assert_called_once()
        finally:
            import os
            os.remove(fpath)

    def test_run_ddl_validation_safe_against_strict_connection_and_ensures_cleanup(self):
        import tempfile
        from unittest.mock import MagicMock
        from validate_postgres_ddl import run_ddl_validation

        with tempfile.NamedTemporaryFile('w', suffix='.sql', delete=False) as f:
            f.write('SELECT 1;\n')
            fpath = f.name

        try:
            # Emulate real C extension connection that rejects arbitrary attribute assignment
            class StrictConnection:
                def __init__(self, cursor):
                    self.autocommit = False
                    self._cursor = cursor
                    self.rolled_back = False
                    self.committed = False

                def cursor(self):
                    return self._cursor

                def rollback(self):
                    self.rolled_back = True

                def commit(self):
                    self.committed = True

                def __setattr__(self, name, value):
                    if name in ('autocommit', '_cursor', 'rolled_back', 'committed'):
                        super().__setattr__(name, value)
                    else:
                        raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")

            mock_cursor = MagicMock()
            strict_conn = StrictConnection(mock_cursor)

            results, runtime_issues, *_ = run_ddl_validation(strict_conn, [fpath], apply_changes=False)
            self.assertEqual(len(results), 1)
            self.assertTrue(results[0].success)
            self.assertTrue(strict_conn.rolled_back)
            mock_cursor.close.assert_called_once()
        finally:
            import os
            os.remove(fpath)

    def test_print_diagnostic_report_empty_returns_false(self):
        from validate_postgres_ddl import print_diagnostic_report
        self.assertFalse(print_diagnostic_report([]))

    def test_mandatory_checker_verifies_messaged_function_and_fails(self):
        """
        P1 regression end-to-end: a function whose body mentions
        'CREATE DOMAIN fake ...' plus an invalid call must be checked by the
        mandatory checker and fail — never conclude success without a target.
        (Before the identify fix, the statement classified as DOMAIN fake,
        the function never became a check target, and the run PASSED.)
        """
        import tempfile
        from unittest.mock import MagicMock
        from validate_postgres_ddl import run_ddl_validation

        ddl = (
            'CREATE FUNCTION "f_msg"() RETURNS void AS $$\n'
            'BEGIN\n'
            "    RAISE NOTICE 'CREATE DOMAIN fake AS integer';\n"
            '    PERFORM * FROM nonexistent_table;\n'
            'END;\n'
            '$$ LANGUAGE plpgsql;\n'
        )
        with tempfile.NamedTemporaryFile('w', suffix='.sql', delete=False) as f:
            f.write(ddl)
            fpath = f.name

        try:
            mock_conn = MagicMock()
            mock_cursor = MagicMock()
            mock_conn.cursor.return_value = mock_cursor
            mock_conn.autocommit = False

            # Extension present; catalog discovers f_msg; checker flags the
            # invalid call inside it.
            mock_cursor.fetchone.return_value = (1,)
            mock_cursor.fetchall.side_effect = [
                [(4242, 'f_msg', 'public', '')],  # pg_proc
                [],                               # pg_trigger
                [("column 'bad_col' does not exist", 'error', '42703', 10,
                  'PERFORM * FROM nonexistent_table;')],
            ]

            from validate_postgres_ddl import CHECK_ISSUES_FOUND
            results, runtime_issues, checker_status = run_ddl_validation(
                mock_conn, [fpath], apply_changes=False, require_checker=True
            )

            # The function was identified (not DOMAIN fake) and checked...
            self.assertTrue(
                any(r.statement.object_name == 'f_msg' and not r.success for r in results),
                f"Expected a failing check result for f_msg, got: {[(r.statement.object_name, r.success) for r in results]}"
            )
            self.assertTrue(any(name == 'f_msg' for name, _ in runtime_issues))
            # ...and the mandatory run reports issues, never success.
            self.assertEqual(checker_status, CHECK_ISSUES_FOUND)
        finally:
            import os
            os.remove(fpath)

    def test_mandatory_checker_verifies_hostile_named_function_and_fails(self):
        """
        P1 regression end-to-end: a function NAMED "CREATE DOMAIN fake" with
        an invalid call must be checked by the mandatory checker and fail —
        never misclassified as DOMAIN fake and skipped to success.
        """
        import tempfile
        from unittest.mock import MagicMock
        from validate_postgres_ddl import run_ddl_validation

        ddl = (
            'CREATE FUNCTION "CREATE DOMAIN fake"() RETURNS void AS $$\n'
            'BEGIN\n'
            "    RAISE NOTICE 'hi';\n"
            '    PERFORM * FROM nonexistent_table;\n'
            'END;\n'
            '$$ LANGUAGE plpgsql;\n'
        )
        with tempfile.NamedTemporaryFile('w', suffix='.sql', delete=False) as f:
            f.write(ddl)
            fpath = f.name

        try:
            mock_conn = MagicMock()
            mock_cursor = MagicMock()
            mock_conn.cursor.return_value = mock_cursor
            mock_conn.autocommit = False

            mock_cursor.fetchone.return_value = (1,)
            mock_cursor.fetchall.side_effect = [
                [(4242, 'CREATE DOMAIN fake', 'public', '')],  # pg_proc
                [],                                            # pg_trigger
                [("relation 'nonexistent_table' does not exist", 'error', '42P01', 10,
                  'PERFORM * FROM nonexistent_table;')],
            ]

            from validate_postgres_ddl import CHECK_ISSUES_FOUND
            results, runtime_issues, checker_status = run_ddl_validation(
                mock_conn, [fpath], apply_changes=False, require_checker=True
            )

            self.assertTrue(
                any(r.statement.object_name == 'CREATE DOMAIN fake' and not r.success
                    for r in results),
                f"Expected a failing check result for the hostile-named function, got: "
                f"{[(r.statement.object_name, r.success) for r in results]}"
            )
            self.assertTrue(any(name == 'CREATE DOMAIN fake' for name, _ in runtime_issues))
            self.assertEqual(checker_status, CHECK_ISSUES_FOUND)
        finally:
            import os
            os.remove(fpath)

    def test_run_ddl_validation_missing_target_file_fails(self):
        from unittest.mock import MagicMock
        from validate_postgres_ddl import run_ddl_validation, print_diagnostic_report
        mock_conn = MagicMock()
        results, *_ = run_ddl_validation(mock_conn, ["/nonexistent/missing_dump.sql"])
        self.assertEqual(len(results), 1)
        self.assertFalse(results[0].success)
        self.assertEqual(results[0].pg_code, "FILE_NOT_FOUND")
        self.assertFalse(print_diagnostic_report(results))

    def test_run_ddl_validation_empty_target_file_fails_by_default(self):
        import tempfile, os
        from unittest.mock import MagicMock
        from validate_postgres_ddl import run_ddl_validation, print_diagnostic_report
        with tempfile.NamedTemporaryFile("w+", suffix=".sql", delete=False) as f:
            f.write("-- comment only\n")
            temp_path = f.name
        self.addCleanup(os.remove, temp_path)

        mock_conn = MagicMock()
        results, *_ = run_ddl_validation(mock_conn, [temp_path], allow_empty_files=False)
        self.assertEqual(len(results), 1)
        self.assertFalse(results[0].success)
        self.assertEqual(results[0].pg_code, "FILE_EMPTY")
        self.assertFalse(print_diagnostic_report(results))


class TestPlpgsqlCheckValidationUnit(unittest.TestCase):
    def test_checker_exception_generates_failure_result_and_savepoint_rollback(self):
        from unittest.mock import MagicMock
        from validate_postgres_ddl import check_plpgsql_runtime_validity, CHECK_ISSUES_FOUND

        mock_cursor = MagicMock()
        mock_cursor.fetchone.return_value = (1,)
        mock_cursor.fetchall.side_effect = [
            [(101, 'sp_fn_crash', 'public', '')],
            [],
        ]

        def execute_side_effect(sql, *_args):
            if 'plpgsql_check_function_tb' in str(sql):
                raise RuntimeError("plpgsql_check internal error / cache lookup failed")

        mock_cursor.execute.side_effect = execute_side_effect

        val_results, issues, status = check_plpgsql_runtime_validity(mock_cursor, ['sp_fn_crash'])
        self.assertEqual(len(val_results), 1)
        self.assertFalse(val_results[0].success)
        self.assertEqual(val_results[0].pg_code, 'CHECKER_EXCEPTION')
        self.assertIn("plpgsql_check internal error", val_results[0].error_message)
        self.assertEqual(status, CHECK_ISSUES_FOUND)
        mock_cursor.execute.assert_any_call("ROLLBACK TO SAVEPOINT sp_plpgsql_check_1;")

    def test_catalog_discovery_failure_does_not_equal_empty_list(self):
        from unittest.mock import MagicMock
        from validate_postgres_ddl import check_plpgsql_runtime_validity, CHECK_NOT_PERFORMED

        mock_cursor = MagicMock()
        mock_cursor.fetchone.return_value = (1,)

        def execute_side_effect(sql, *_args):
            if 'FROM pg_proc p' in str(sql):
                raise RuntimeError("permission denied for table pg_proc")

        mock_cursor.execute.side_effect = execute_side_effect

        val_results, issues, status = check_plpgsql_runtime_validity(mock_cursor)
        self.assertEqual(len(val_results), 1)
        self.assertFalse(val_results[0].success)
        self.assertEqual(val_results[0].pg_code, 'CATALOG_DISCOVERY_FAILED')
        self.assertIn("permission denied for table pg_proc", val_results[0].error_message)
        self.assertEqual(status, CHECK_NOT_PERFORMED)
        mock_cursor.execute.assert_any_call("ROLLBACK TO SAVEPOINT sp_discover_funcs;")

    def test_missing_extension_reports_not_performed_and_blocks_if_required(self):
        from unittest.mock import MagicMock
        from validate_postgres_ddl import check_plpgsql_runtime_validity, CHECK_NOT_PERFORMED

        mock_cursor = MagicMock()
        mock_cursor.fetchone.return_value = None  # Extension missing

        # Case 1: require_checker = False
        val_results, issues, status = check_plpgsql_runtime_validity(mock_cursor, require_checker=False)
        self.assertEqual(val_results, [])
        self.assertEqual(status, CHECK_NOT_PERFORMED)
        self.assertEqual(len(issues), 1)
        self.assertIn("verificação não realizada", issues[0][1])

        # Case 2: require_checker = True
        val_results, issues, status = check_plpgsql_runtime_validity(mock_cursor, require_checker=True)
        self.assertEqual(len(val_results), 1)
        self.assertFalse(val_results[0].success)
        self.assertEqual(val_results[0].pg_code, "CHECKER_REQUIRED")
        self.assertEqual(status, CHECK_NOT_PERFORMED)

    def test_two_objects_first_failing_preserves_transaction_and_checks_second(self):
        from unittest.mock import MagicMock
        from validate_postgres_ddl import check_plpgsql_runtime_validity, CHECK_ISSUES_FOUND

        mock_cursor = MagicMock()
        mock_cursor.fetchone.return_value = (1,)
        mock_cursor.fetchall.side_effect = [
            [(101, 'fn_bad', 'public', ''), (102, 'fn_good', 'public', '')],
            [],  # triggers
            [],  # fn_good check returns []
        ]

        def execute_side_effect(sql, *args):
            if 'plpgsql_check_function_tb' in str(sql):
                if args and len(args[0]) >= 1 and args[0][0] == 101:
                    raise RuntimeError("Error checking fn_bad")

        mock_cursor.execute.side_effect = execute_side_effect

        val_results, issues, status = check_plpgsql_runtime_validity(mock_cursor)
        self.assertEqual(len(val_results), 1)
        self.assertFalse(val_results[0].success)
        self.assertEqual(val_results[0].statement.object_name, 'fn_bad')
        self.assertEqual(status, CHECK_ISSUES_FOUND)
        mock_cursor.execute.assert_any_call("ROLLBACK TO SAVEPOINT sp_plpgsql_check_1;")
        mock_cursor.execute.assert_any_call("SAVEPOINT sp_plpgsql_check_2;")

    def test_zero_targets_when_functions_expected_fails_if_require_checker_true(self):
        from unittest.mock import MagicMock
        from validate_postgres_ddl import check_plpgsql_runtime_validity, CHECK_ISSUES_FOUND

        mock_cursor = MagicMock()
        mock_cursor.fetchone.return_value = (1,)  # Extension present
        mock_cursor.fetchall.side_effect = [
            [],  # 0 regular functions found in catalog
            [],  # 0 triggers found in catalog
        ]

        val_results, issues, status = check_plpgsql_runtime_validity(
            mock_cursor,
            function_names=['p-with-dash'],
            require_checker=True
        )
        self.assertEqual(len(val_results), 1)
        self.assertFalse(val_results[0].success)
        self.assertEqual(val_results[0].pg_code, 'TARGET_NOT_VERIFIED')
        self.assertIn("Alvo obrigatório 'p-with-dash' não foi verificado", val_results[0].error_message)
        self.assertEqual(status, CHECK_ISSUES_FOUND)
        self.assertTrue(any("alvo não verificado" in iss[1] for iss in issues))

    def test_zero_targets_when_functions_expected_reports_issue_and_does_not_pass(self):
        from unittest.mock import MagicMock
        from validate_postgres_ddl import check_plpgsql_runtime_validity, CHECK_ISSUES_FOUND

        mock_cursor = MagicMock()
        mock_cursor.fetchone.return_value = (1,)  # Extension present
        mock_cursor.fetchall.side_effect = [
            [],  # 0 regular functions found in catalog
            [],  # 0 triggers found in catalog
        ]

        val_results, issues, status = check_plpgsql_runtime_validity(
            mock_cursor,
            function_names=['p-with-dash'],
            require_checker=False
        )
        self.assertEqual(status, CHECK_ISSUES_FOUND)
        self.assertTrue(any("alvo não verificado" in iss[1] for iss in issues))


class DbCursorProxy:
    def __init__(self, real_cur, execute_hook=None, fetchone_hook=None):
        self._cur = real_cur
        self._execute_hook = execute_hook
        self._fetchone_hook = fetchone_hook

    def execute(self, sql, params=None):
        if self._execute_hook:
            return self._execute_hook(self._cur, sql, params)
        return self._cur.execute(sql, params) if params is not None else self._cur.execute(sql)

    def fetchone(self):
        if self._fetchone_hook:
            return self._fetchone_hook(self._cur)
        return self._cur.fetchone()

    def fetchall(self):
        return self._cur.fetchall()

    def close(self):
        return self._cur.close()


class DbConnProxy:
    def __init__(self, real_conn, cursor_factory):
        self._conn = real_conn
        self._cursor_factory = cursor_factory

    def cursor(self, *args, **kwargs):
        real_cur = self._conn.cursor(*args, **kwargs)
        return self._cursor_factory(real_cur)

    def commit(self):
        return self._conn.commit()

    def rollback(self):
        return self._conn.rollback()

    def close(self):
        return self._conn.close()

    @property
    def closed(self):
        return self._conn.closed

    @property
    def autocommit(self):
        return self._conn.autocommit

    @autocommit.setter
    def autocommit(self, val):
        self._conn.autocommit = val


@requires_postgres_class
class TestValidatePostgresDdlRegression(unittest.TestCase):
    """
    Regression tests calling the complete public validate_postgres_ddl() function
    against a real PostgreSQL database with a disposable schema.
    Verifies return values, diagnostic report output, connection ownership,
    and PostgreSQL catalog state across dry-run and apply modes.
    """

    def setUp(self):
        require_live_postgres(self)
        self.conn = get_test_postgres_connection()
        self.schema_name = unique_name("test_disposable_val")
        cur = self.conn.cursor()
        cur.execute(f"DROP SCHEMA IF EXISTS {self.schema_name} CASCADE;")
        cur.execute(f"CREATE SCHEMA {self.schema_name};")
        cur.execute("CREATE EXTENSION IF NOT EXISTS plpgsql_check;")
        cur.execute(f"SET search_path TO {self.schema_name}, public;")
        self.conn.commit()

    def tearDown(self):
        if self.conn and not self.conn.closed:
            try:
                cur = self.conn.cursor()
                cur.execute(f"DROP SCHEMA IF EXISTS {self.schema_name} CASCADE;")
                self.conn.commit()
            except psycopg2.Error:
                pass
            finally:
                self.conn.close()

    def test_complete_public_function_valid_ddl_dry_run_never_persists(self):
        import tempfile, os
        from validate_postgres_ddl import validate_postgres_ddl

        with tempfile.NamedTemporaryFile("w+", suffix=".sql", delete=False) as f:
            f.write("CREATE TABLE reg_dry_run_table (id INT PRIMARY KEY, name VARCHAR(50));\n")
            fpath = f.name
        self.addCleanup(os.remove, fpath)

        success = validate_postgres_ddl(
            pg_connection=self.conn,
            target_files=[fpath],
            apply_changes=False
        )
        self.assertTrue(success)
        # Caller's connection must remain open and under caller responsibility
        self.assertFalse(self.conn.closed)

        # Verify catalog: table must NOT have been persisted in dry-run mode
        cur = self.conn.cursor()
        cur.execute(
            f"SELECT 1 FROM information_schema.tables "
            f"WHERE table_schema = '{self.schema_name}' AND table_name = 'reg_dry_run_table';"
        )
        self.assertIsNone(cur.fetchone())

    def test_complete_public_function_valid_ddl_apply_persists_in_catalog(self):
        import tempfile, os
        from validate_postgres_ddl import validate_postgres_ddl

        with tempfile.NamedTemporaryFile("w+", suffix=".sql", delete=False) as f:
            f.write("CREATE TABLE reg_apply_table (id INT PRIMARY KEY, name VARCHAR(50));\n")
            fpath = f.name
        self.addCleanup(os.remove, fpath)

        success = validate_postgres_ddl(
            pg_connection=self.conn,
            target_files=[fpath],
            apply_changes=True
        )
        self.assertTrue(success)
        self.assertFalse(self.conn.closed)

        # Verify catalog: table MUST have been persisted in apply mode
        cur = self.conn.cursor()
        cur.execute(
            f"SELECT 1 FROM information_schema.tables "
            f"WHERE table_schema = '{self.schema_name}' AND table_name = 'reg_apply_table';"
        )
        row = cur.fetchone()
        self.assertIsNotNone(row)
        self.assertEqual(row[0], 1)

    def test_complete_public_function_invalid_ddl_apply_reverts_all_changes(self):
        import tempfile, os
        from validate_postgres_ddl import validate_postgres_ddl

        with tempfile.NamedTemporaryFile("w+", suffix=".sql", delete=False) as f:
            # Statement 1 valid, Statement 2 syntax error
            f.write(
                "CREATE TABLE reg_first_ok (id INT PRIMARY KEY);\n"
                "CREATE TABLE reg_second_bad (id INT INVALID_SYNTAX);\n"
            )
            fpath = f.name
        self.addCleanup(os.remove, fpath)

        success = validate_postgres_ddl(
            pg_connection=self.conn,
            target_files=[fpath],
            apply_changes=True
        )
        self.assertFalse(success)
        self.assertFalse(self.conn.closed)

        # Verify catalog: all changes rolled back; Statement 1 must NOT exist
        cur = self.conn.cursor()
        cur.execute(
            f"SELECT 1 FROM information_schema.tables "
            f"WHERE table_schema = '{self.schema_name}' AND table_name = 'reg_first_ok';"
        )
        self.assertIsNone(cur.fetchone())

    def test_complete_public_function_report_signature_and_runtime_issues_formatting(self):
        from validate_postgres_ddl import print_diagnostic_report, ValidationResult, SQLStatement

        stmt = SQLStatement("test.sql", "FUNCTION", "sp_demo", "SELECT 1;", 1)
        results = [ValidationResult(stmt, success=True)]
        runtime_issues = [("sp_demo", "Line 4: table test does not exist")]

        # Calling print_diagnostic_report with runtime_issues must succeed without TypeError
        ret = print_diagnostic_report(results, runtime_issues=runtime_issues)
        self.assertTrue(ret)

    def test_presentation_failure_does_not_claim_rollback_when_committed(self):
        import tempfile, os
        from unittest.mock import patch
        from validate_postgres_ddl import validate_postgres_ddl

        with tempfile.NamedTemporaryFile("w+", suffix=".sql", delete=False) as f:
            f.write("CREATE TABLE reg_tbl_pres (id INT PRIMARY KEY);\n")
            fpath = f.name
        self.addCleanup(os.remove, fpath)

        # Simulate presentation failure after successful commit
        with patch('validate_postgres_ddl.print_diagnostic_report', side_effect=RuntimeError("Formatting crash")):
            import io
            from contextlib import redirect_stdout
            out = io.StringIO()
            with redirect_stdout(out):
                success = validate_postgres_ddl(
                    pg_connection=self.conn,
                    target_files=[fpath],
                    apply_changes=True
                )
            self.assertFalse(success)
            output_str = out.getvalue()
            # Must accurately indicate changes WERE committed, not that a rollback occurred
            self.assertIn("changes WERE committed", output_str)
            self.assertNotIn("rolled back all changes", output_str)

    def test_function_with_nonexistent_column_fails_validation_and_blocks_commit(self):
        import tempfile, os
        from validate_postgres_ddl import validate_postgres_ddl

        with tempfile.NamedTemporaryFile("w+", suffix=".sql", delete=False) as f:
            f.write(
                "CREATE TABLE reg_tbl_bad (id INT PRIMARY KEY, name VARCHAR(50));\n"
                "CREATE FUNCTION reg_fn_broken() RETURNS void AS $$\n"
                "BEGIN\n"
                "    SELECT non_existent_col FROM reg_tbl_bad;\n"
                "END;\n"
                "$$ LANGUAGE plpgsql;\n"
            )
            fpath = f.name
        self.addCleanup(os.remove, fpath)

        success = validate_postgres_ddl(
            pg_connection=self.conn,
            target_files=[fpath],
            apply_changes=True
        )
        self.assertFalse(success)
        self.assertFalse(self.conn.closed)

        # Confirm rollback: neither table nor function were persisted
        cur = self.conn.cursor()
        cur.execute(
            f"SELECT 1 FROM information_schema.tables "
            f"WHERE table_schema = '{self.schema_name}' AND table_name = 'reg_tbl_bad';"
        )
        self.assertIsNone(cur.fetchone())

    def test_two_objects_first_failing_preserves_transaction_for_second_diagnostic(self):
        import tempfile, os
        from validate_postgres_ddl import run_ddl_validation, CHECK_ISSUES_FOUND

        with tempfile.NamedTemporaryFile("w+", suffix=".sql", delete=False) as f:
            f.write(
                "CREATE TABLE reg_two_tbl (id INT PRIMARY KEY);\n"
                "CREATE FUNCTION reg_two_bad1() RETURNS void AS $$\n"
                "BEGIN\n"
                "    SELECT bad_c1 FROM reg_two_tbl;\n"
                "END;\n"
                "$$ LANGUAGE plpgsql;\n"
                "CREATE FUNCTION reg_two_bad2() RETURNS void AS $$\n"
                "BEGIN\n"
                "    SELECT bad_c2 FROM reg_two_tbl;\n"
                "END;\n"
                "$$ LANGUAGE plpgsql;\n"
            )
            fpath = f.name
        self.addCleanup(os.remove, fpath)

        results, runtime_issues, status = run_ddl_validation(
            conn=self.conn,
            target_files=[fpath],
            apply_changes=False
        )
        self.assertEqual(status, CHECK_ISSUES_FOUND)
        failed_names = [r.statement.object_name for r in results if not r.success]
        self.assertIn("reg_two_bad1", failed_names)
        self.assertIn("reg_two_bad2", failed_names)
        self.assertTrue(len(runtime_issues) >= 2)

    def test_overloaded_functions_checked_by_distinct_oids(self):
        import tempfile, os
        from validate_postgres_ddl import run_ddl_validation, CHECK_ISSUES_FOUND

        with tempfile.NamedTemporaryFile("w+", suffix=".sql", delete=False) as f:
            f.write(
                "CREATE TABLE reg_ovl_tbl (id INT PRIMARY KEY);\n"
                "CREATE FUNCTION reg_ovl(a int) RETURNS int AS $$\n"
                "BEGIN\n"
                "    RETURN a + 1;\n"
                "END;\n"
                "$$ LANGUAGE plpgsql;\n"
                "CREATE FUNCTION reg_ovl(a text) RETURNS text AS $$\n"
                "BEGIN\n"
                "    SELECT bad_col_in_ovl FROM reg_ovl_tbl;\n"
                "    RETURN a;\n"
                "END;\n"
                "$$ LANGUAGE plpgsql;\n"
            )
            fpath = f.name
        self.addCleanup(os.remove, fpath)

        results, runtime_issues, status = run_ddl_validation(
            conn=self.conn,
            target_files=[fpath],
            apply_changes=False
        )
        self.assertEqual(status, CHECK_ISSUES_FOUND)
        failed_msgs = " ".join(r.error_message for r in results if not r.success)
        self.assertIn("bad_col_in_ovl", failed_msgs)

    def test_trigger_dependent_on_new_validates_against_table_columns(self):
        import tempfile, os
        from validate_postgres_ddl import validate_postgres_ddl

        with tempfile.NamedTemporaryFile("w+", suffix=".sql", delete=False) as f:
            f.write(
                "CREATE TABLE reg_trg_tbl (id INT PRIMARY KEY, val VARCHAR(50));\n"
                "CREATE OR REPLACE FUNCTION reg_trg_fn() RETURNS trigger AS $$\n"
                "BEGIN\n"
                "    NEW.invalid_column_on_table = 'bad';\n"
                "    RETURN NEW;\n"
                "END;\n"
                "$$ LANGUAGE plpgsql;\n"
                "CREATE TRIGGER reg_trg_obj BEFORE INSERT ON reg_trg_tbl FOR EACH ROW EXECUTE FUNCTION reg_trg_fn();\n"
            )
            fpath = f.name
        self.addCleanup(os.remove, fpath)

        success = validate_postgres_ddl(
            pg_connection=self.conn,
            target_files=[fpath],
            apply_changes=True
        )
        self.assertFalse(success)
        # Commit must be blocked, table must not exist
        cur = self.conn.cursor()
        cur.execute(
            f"SELECT 1 FROM information_schema.tables "
            f"WHERE table_schema = '{self.schema_name}' AND table_name = 'reg_trg_tbl';"
        )
        self.assertIsNone(cur.fetchone())

    def test_checker_exception_blocks_commit_in_apply_mode(self):
        import tempfile, os
        from validate_postgres_ddl import validate_postgres_ddl

        with tempfile.NamedTemporaryFile("w+", suffix=".sql", delete=False) as f:
            f.write(
                "CREATE TABLE reg_tbl_exc (id INT PRIMARY KEY);\n"
                "CREATE FUNCTION reg_fn_exc() RETURNS void AS $$\n"
                "BEGIN\n"
                "    NULL;\n"
                "END;\n"
                "$$ LANGUAGE plpgsql;\n"
            )
            fpath = f.name
        self.addCleanup(os.remove, fpath)

        def execute_hook(real_cur, sql, params):
            if 'plpgsql_check_function_tb' in str(sql):
                raise RuntimeError("Simulated checker runtime exception")
            return real_cur.execute(sql, params) if params is not None else real_cur.execute(sql)

        proxy_conn = DbConnProxy(self.conn, lambda c: DbCursorProxy(c, execute_hook=execute_hook))
        success = validate_postgres_ddl(
            pg_connection=proxy_conn,
            target_files=[fpath],
            apply_changes=True
        )
        self.assertFalse(success)

        # Must not have been persisted
        cur = self.conn.cursor()
        cur.execute(
            f"SELECT 1 FROM information_schema.tables "
            f"WHERE table_schema = '{self.schema_name}' AND table_name = 'reg_tbl_exc';"
        )
        self.assertIsNone(cur.fetchone())

    def test_missing_extension_reports_not_performed_and_blocks_if_required(self):
        import tempfile, os
        from validate_postgres_ddl import validate_postgres_ddl

        with tempfile.NamedTemporaryFile("w+", suffix=".sql", delete=False) as f:
            f.write("CREATE TABLE reg_tbl_req (id INT PRIMARY KEY);\n")
            fpath = f.name
        self.addCleanup(os.remove, fpath)

        def make_cur(real_cur):
            last_sql = {"val": ""}
            def exec_hook(c, sql, params):
                last_sql["val"] = str(sql)
                return c.execute(sql, params) if params is not None else c.execute(sql)
            def fetchone_hook(c):
                if 'pg_extension' in last_sql["val"]:
                    return None
                return c.fetchone()
            return DbCursorProxy(real_cur, execute_hook=exec_hook, fetchone_hook=fetchone_hook)

        proxy_conn = DbConnProxy(self.conn, make_cur)

        # When require_checker is True, missing extension MUST block commit
        success_req = validate_postgres_ddl(
            pg_connection=proxy_conn,
            target_files=[fpath],
            apply_changes=True,
            require_checker=True
        )
        self.assertFalse(success_req)

        cur = self.conn.cursor()
        cur.execute(
            f"SELECT 1 FROM information_schema.tables "
            f"WHERE table_schema = '{self.schema_name}' AND table_name = 'reg_tbl_req';"
        )
        self.assertIsNone(cur.fetchone())

    def test_function_with_hyphen_in_name_and_invalid_sql_fails_with_require_checker(self):
        """
        Regression: Function with hyphen in name ('p-with-dash') and invalid internal SQL
        must be properly identified, targeted by plpgsql_check, and rejected when require_checker=True.
        """
        import tempfile, os
        from validate_postgres_ddl import validate_postgres_ddl

        with tempfile.NamedTemporaryFile("w+", suffix=".sql", delete=False) as f:
            f.write(
                "CREATE TABLE reg_tbl_dash (id INT PRIMARY KEY);\n"
                'CREATE FUNCTION "p-with-dash"() RETURNS void AS $$\n'
                "BEGIN\n"
                "    SELECT non_existent_col FROM reg_tbl_dash;\n"
                "END;\n"
                "$$ LANGUAGE plpgsql;\n"
            )
            fpath = f.name
        self.addCleanup(os.remove, fpath)

        success = validate_postgres_ddl(
            pg_connection=self.conn,
            target_files=[fpath],
            apply_changes=True,
            require_checker=True
        )
        self.assertFalse(success, "Function 'p-with-dash' with invalid SQL must fail validation")

        # Confirm rollback: neither table nor function were persisted
        cur = self.conn.cursor()
        cur.execute(
            f"SELECT 1 FROM information_schema.tables "
            f"WHERE table_schema = '{self.schema_name}' AND table_name = 'reg_tbl_dash';"
        )
        self.assertIsNone(cur.fetchone(), "Table must be rolled back on checker failure")

    def test_function_with_space_in_name_and_invalid_sql_fails_with_require_checker(self):
        """
        Regression: Function with space in name ('func with space') and invalid internal SQL
        must be properly identified, targeted by plpgsql_check, and rejected when require_checker=True.
        """
        import tempfile, os
        from validate_postgres_ddl import validate_postgres_ddl

        with tempfile.NamedTemporaryFile("w+", suffix=".sql", delete=False) as f:
            f.write(
                "CREATE TABLE reg_tbl_space (id INT PRIMARY KEY);\n"
                'CREATE FUNCTION "func with space"() RETURNS void AS $$\n'
                "BEGIN\n"
                "    SELECT non_existent_col FROM reg_tbl_space;\n"
                "END;\n"
                "$$ LANGUAGE plpgsql;\n"
            )
            fpath = f.name
        self.addCleanup(os.remove, fpath)

        success = validate_postgres_ddl(
            pg_connection=self.conn,
            target_files=[fpath],
            apply_changes=True,
            require_checker=True
        )
        self.assertFalse(success, "Function 'func with space' with invalid SQL must fail validation")

        # Confirm rollback
        cur = self.conn.cursor()
        cur.execute(
            f"SELECT 1 FROM information_schema.tables "
            f"WHERE table_schema = '{self.schema_name}' AND table_name = 'reg_tbl_space';"
        )
        self.assertIsNone(cur.fetchone(), "Table must be rolled back on checker failure")


if __name__ == '__main__':
    unittest.main()
