import unittest

from validate_postgres_ddl import identify_object


class TestIdentifyObject(unittest.TestCase):
    def test_domain_schema_qualified_quoted_in_do_block(self):
        # Format generated by DdlExporter: DO block wrapping the CREATE DOMAIN
        sql = (
            'DO $$\n'
            'BEGIN\n'
            "    IF NOT EXISTS (SELECT 1 FROM pg_type t) THEN\n"
            "        EXECUTE 'CREATE DOMAIN public.\"varchar20\" AS VARCHAR(20);';\n"
            '    END IF;\n'
            'END $$;'
        )
        self.assertEqual(identify_object(sql), ('DOMAIN', 'varchar20'))

    def test_domain_plain_quoted(self):
        self.assertEqual(identify_object('CREATE DOMAIN "meu_dominio" AS INTEGER;'),
                         ('DOMAIN', 'meu_dominio'))

    def test_domain_bare_unquoted(self):
        self.assertEqual(identify_object('CREATE DOMAIN MEU_DOMINIO AS INTEGER;'),
                         ('DOMAIN', 'MEU_DOMINIO'))

    def test_domain_with_hyphen(self):
        self.assertEqual(identify_object("CREATE DOMAIN public.\"e-mail\" AS VARCHAR(50);"),
                         ('DOMAIN', 'e-mail'))

    def test_view(self):
        self.assertEqual(
            identify_object('DROP VIEW IF EXISTS "MINHA_VIEW" CASCADE;\nCREATE VIEW "MINHA_VIEW" AS SELECT 1;'),
            ('VIEW', 'MINHA_VIEW'))

    def test_function(self):
        sql = ('CREATE FUNCTION "minha_func"() RETURNS void AS $$\n'
               'BEGIN\n'
               'END;\n'
               '$$ LANGUAGE plpgsql;')
        self.assertEqual(identify_object(sql), ('FUNCTION', 'minha_func'))

    def test_trigger(self):
        self.assertEqual(
            identify_object('DROP TRIGGER IF EXISTS "TRG_X" ON "tabela";\n'
                            'CREATE TRIGGER "TRG_X" BEFORE INSERT ON "tabela" FOR EACH ROW EXECUTE FUNCTION f();'),
            ('TRIGGER', 'TRG_X'))

    def test_other_statement(self):
        self.assertEqual(identify_object('SELECT 1;'), ('OTHER', 'UNKNOWN'))


if __name__ == '__main__':
    unittest.main()
